### PR TITLE
add https support to elasticsearch collector without breaking existing configs

### PR DESCRIPTION
**Pull request by imreACTmd**
ElasticSearch now has SSL/TLS/HTTPS support via several means: Shield, SearchGuard. 

This patch allows specifying the connection scheme which was previously hardcoded as HTTP. 

The default scheme is still HTTP but now it can also be specified as HTTPS.

### CODE REVIEW

**Comment by shortdudey123** [comment]
Can you fix the pep8 error?
`src/collectors/elasticsearch/elasticsearch.py:229:81: E501 line too long (87 > 80 characters)`


Also, can you update the doc with the new config option?

**Comment by imreFitos** [comment]
Thank you for the quick feedback, updated PR

**Comment by shortdudey123** [comment]
LGTM

@jaingaurav can you review?

**Comment by bmhatfield** [comment]
Thanks for this change!

**Pull request merged**
