### PR TITLE
(minor) add ncpus metric - amount of CPU threads

### PR DESCRIPTION
**Pull request by Cka3o4Huk**
Hi,

This is micro-minor pull request to add metric 'ncpus' for CPU collector. It's quite useful to have this metric. If CPU collector reports only totals, i.e. %, ncpus provides information about amount of used cores / threads.

### CODE REVIEW

**Comment by Cka3o4Huk** [comment]
Hi,
Could you please have a look?
Thank you in advance!

**Comment by jaingaurav** [comment]
@Cka3o4Huk This looks reasonable =, however could you add a metric for the psutil code path? Also 'cpu_count' may be a better name than ncpus

**Comment by steenzout** [comment]
@jaingaurav what do you mean by `could you add a metric for the psutil code path?` ?

**Comment by jaingaurav** [comment]
@steenzout: So this collector works in 2 modes, reading from `/proc` and using `psutils` (see the `if` and `else` statements on line 90 & 190).

What I was asking for was the `ncpus` metric to be computed and generated in the `psutils` `else` statement. This PR currently only handles the `/proc` code path.

**Comment by steenzout** [comment]
@jaingaurav got it.
I'm testing a new PR for this...

**Comment by jaingaurav** [comment]
@steenzout: Thanks. Unit tests would be great too :)

**Comment by steenzout** [comment]
@jaingaurav I'll put on my TODO list. still getting acquainted with the code :)

**Comment by jaingaurav** [comment]
Thanks @steenzout let me know if there is any way I can help.

**Pull request closed without merging**
