### PR TITLE
[portstat] fix missing 'PortStatCollector' in get_port_stats method call

### PR DESCRIPTION
**Pull request by Nihn**

### CODE REVIEW

**Comment by mzupan** [comment]
@Nihn looks like we might also need to add self into the function above too

**Comment by Nihn** [comment]
What do you mean? I don't see where :).

**Comment by jaingaurav** [comment]
Did you mean the get_port_stats function signature? If so, I don't think it needs it because its a static method.

**Comment by mattrobenolt** [comment]
`self` isn't right. It's a static method.

If anything, switch it to `PortStatCollector.get_port_stats(port)`.

**Comment by mattrobenolt** [comment]
OR, just move `get_port_stats` off of the class entirely and just use it like a normal function instead of a method.

**Comment by Nihn** [comment]
self is 100% valid but ill do as you wish :).

**Comment by mattrobenolt** [comment]
> self is 100% valid but ill do as you wish :).

I didn't say it wasn't valid, but it's not right. :)

**Comment by mattrobenolt** [comment]
thx :cake: :sparkles:

**Pull request merged**
