### PR TITLE
Add passenger metrics

### PR DESCRIPTION
**Pull request by yydoow**
Following metrics to be added in the collector
- total_apache_procs
- total_passenger_procs
- total_nginx_procs

Following queue size metrics are being reported through
passenger-status.
- top_level_queue_size
- passenger_queue_size

So new configuration file of PassengerCollector will generate

### CODE REVIEW

**Comment by shortdudey123** [comment]
Can you update the testing and doc?

**Comment by yydoow** [comment]
@shortdudey123 , I didn't find doc on how to update the testing and doc, sorry. where can I get it

**Comment by shortdudey123** [comment]
For each collector, the tests are in the `test` directory of the collector (i.e. `src/collectors/passenger_stats/test`) and the docs are in `docs/collectors`.

The docs are auto generated by running the following (this will do all collectors but you can narrow it to only 1 with flags)

```
python build_doc.py
python test.py
```

**Comment by yydoow** [comment]
For docs generating, it updates all the docs, Strange!! 

[root@codo-dmz-puppetmaster,i-c82157f0 Diamond]# python2.7 build_doc.py -c /etc/diamond/diamond.conf -C passenger_stats
Processing AmavisCollector...
Processing ApcupsdCollector...
Processing AuroraCollector...
No __doc__ string!
Processing BeanstalkdCollector...

And for testing 

ERROR: test_get_port_stats (test_portstat.GetPortStatsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock.py", line 1193, in patched
    arg = patching.__enter__()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1268, in __enter__
    original, local = self.get_original()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1242, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: None does not have the attribute 'net_connections'

======================================================================
FAIL: test_docker_stats_method_exists (testdocker_collector.TestDockerCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/woody.yang/Diamond/src/collectors/docker_collector/test/testdocker_collector.py", line 45, in test_docker_stats_method_exists
    self.assertTrue("stats" in dir(Client))
AssertionError: False is not true

======================================================================
FAIL: test_collect (test_portstat.PortStatCollectorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/woody.yang/Diamond/src/collectors/portstat/tests/test_portstat.py", line 43, in test_collect
    any_order=True)
  File "/usr/lib/python2.7/site-packages/mock.py", line 877, in assert_has_calls
    '%r not all found in call list' % (tuple(not_found),)
AssertionError: (call(5222), call(8888)) not all found in call list

**Comment by rtoma** [comment]
Retriggered travis because of `sh: 1: cython: not found` issue.

**Comment by williamjoy** [comment]
@shortdudey123 doc updated, can you review please ?

**Pull request merged**
