### PR TITLE
trend_emic: New collector

### PR DESCRIPTION
**Pull request by randomvariable**
This could be too esoteric for inclusion, but the following collector adds support for a type of interface for 3-phase electricity meters seen in some installations.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
I'm a -1 since this means someone will need to maintain this collector and pretty sure nobody is even capable of doing that. Also no tests to even begin asserting that it's correct behavior.

**Comment by randomvariable** [comment]
That's fine. Withdrawing.

**Comment by mzupan** [comment]
maybe have a wiki entry for 3rd party collectors like this and have some easy way to install them.

**Comment by randomvariable** [comment]
Might be nice to support multiple entries for "collectors_path", so you could store custom collectors in /etc/diamond/collector_modules, for example.

**Pull request closed without merging**
