### PR TITLE
Setting a precision for publish for sub MS ping times

### PR DESCRIPTION
**Pull request by mzupan**
I needed to test ping times from servers to memcache servers in
SoftLayers network. We’d get > 50ms ping times randomly and bids would
fail taking too long to connect to memcache.

It’s possible to have sub MS response times as seen

```
64 bytes from memcache101.domain.com (10.102.74.173): icmp_seq=1 ttl=64
time=0.157 ms
64 bytes from memcache101.domain.com (10.102.74.173): icmp_seq=2 ttl=64
time=0.148 ms
64 bytes from memcache101.domain.com (10.102.74.173): icmp_seq=3 ttl=64
time=0.155 ms
64 bytes from memcache101.domain.com (10.102.74.173): icmp_seq=4 ttl=64
time=0.124 ms
```

without the precision in there it would send metric to graphite like

0.0000

### CODE REVIEW

**Comment by josegonzalez** [comment]
What was the precision previously? If it wasn't 4, can you make the previous version a default and add a config option for precision to the collector?

**Comment by mzupan** [comment]
precision=0 by default. The issue is any ping under 1ms becomes 0.0 due to it. All the tests still work so I don't see a need to set that as a feature. It'll just lead to issues where people over look that setting

**Comment by jaingaurav** [comment]
@mzupan: I think we can merge this PR in. Could you please squash the commits before we do so?

**Comment by shortdudey123** [comment]
I would prefer to use #124 instead.

**Pull request closed without merging**
