### PR TITLE
CPUCollector doesn't honor percore config var

### LINKED ISSUE #70: CPUCollector doesn't honor percore config variable for psutil collections
If you don't have /proc/stat present, CPUCollector will fallback to using 'psutil' to get the CPU data.

Unfortunately, only the /proc/stat codepath checks the 'percore' config variable.

Easy fix; will push one shortly.

### PR DESCRIPTION
**Pull request by jamesmulcahy**
Fixes #70

### CODE REVIEW

**Comment by josegonzalez** [comment]
Any chance you can add a test for this?

**Comment by jaingaurav** [comment]
@jamesmulcahy Any chance you could provide test cases?

**Comment by jamesmulcahy** [comment]
Sorry, don't see myself getting back to this.  I don't use diamond anymore, which means it's non-trivial for me to do this.  You're welcome to close if that suits.

**Comment by jaingaurav** [comment]
Thanks for syncing back with us @jamesmulcahy. I leave this open for a while in case someone decides to pick up on it.

**Comment by shortdudey123** [comment]
Looks like this was already handled in master.  Closing . . .

**Pull request closed without merging**
