### PR TITLE
Update classes.py

### PR DESCRIPTION
**Pull request by Slach**
remove built-in filter function usage
see https://github.com/python-diamond/Diamond/issues/266

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Going to review today and make sure this is the correct fix.

Sorry about that. :(

**Comment by jaingaurav** [comment]
Isn't the correct fix to re-add the lost `filter` parameter in `load_collectors()` and pass it to `load_collectors_from_paths()`

**Comment by jaingaurav** [comment]
Also, clearly a test case was missing here :(

**Comment by Slach** [comment]
i'm re-add filter parameter
but i don't have skills for add clear test case ;) sorry

**Comment by jaingaurav** [comment]
So after taking a closer look. My suggestion for the latter changes was wrong. It doesn't seem like the `filter` parameter is being used anymore. I've manually merged the initial commit.

Thanks for the PR.

**Comment by Tibingeo** [comment]
We are running a diamond collector to collect system metrics and show it on a graph. However, when I try to run the service using service diamond start, it will start but immediately get terminated. I tried to find the log. Syslog says init: diamond main process (32501) terminated with status 1

The following are the /etc/log/diamond/diamond.log

2016-09-11 08:07:25,649] [MainThread] Can not find collector AppMetricCollector

 [2016-09-11 08:07:29,713] [MainThread] Collector failed! Traceback (most recent call last): File "/usr/lib/pymodules/python2.7/diamond/utils/scheduler.py", line 73, in collector_process .....

**Pull request closed without merging**
