### PR TITLE
Adding trove classifiers.

### PR DESCRIPTION
**Pull request by nickjacobson**

### CODE REVIEW

**Comment by nickjacobson** [comment]
See https://github.com/python-diamond/Diamond/issues/486

**Comment by redref** [comment]
Hi,

Diamond is not python3 compatible (maybe one day). I think package naming is automatic.

**Comment by shortdudey123** [comment]
Can you squash your 2 commits? thanks!

**Comment by nickjacobson** [comment]
...actually I'm not sure how to do that, sorry.

**Comment by shortdudey123** [comment]
@nickjacobson hope this helps
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Pull request closed without merging**
