### PR TITLE
fix for dupe datapoints in mongodb collector

### PR DESCRIPTION
**Pull request by rtoma**
this regression was introduced in https://github.com/python-diamond/Diamond/commit/9b716164799b4f4a24c6ac7147f71932a7a6dd24

### CODE REVIEW

**Comment by shortdudey123** [comment]
@rtoma can you elaborate on which data points were duplicated? all? database related? collection related?

**Comment by rtoma** [comment]
Hi @shortdudey123,

Only the serverStatus metrics were duplicated. Have a look at https://github.com/python-diamond/Diamond/commit/9b716164799b4f4a24c6ac7147f71932a7a6dd24#diff-6d354e8462744ef312387af70b6ff672R190 - thats the commit where a 2nd `_publish_transformed` call appeared. I am guessing a copy/paste error.

Without my bugfix in mongodb.py the unittest will fail printing the duplicated serverStatus metrics:
```
======================================================================
FAIL: test_should_publish_keys_from_real_server_stats (testmongodb.TestMongoDBCollector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rtoma/projects/diamond-bolcom/env/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/Users/rtoma/projects/diamond-bolcom/src/collectors/mongodb/test/testmongodb.py", line 183, in test_should_publish_keys_from_real_server_stats
    ', '.join(dupes))
AssertionError: BUG: 1+ point for same metric received: opcounters_per_sec.delete, \
network_per_sec.numRequests, opcounters_per_sec.query, opcountersRepl_per_sec.delete, \
opcounters_per_sec.command, opcountersRepl_per_sec.insert, network_per_sec.bytesOut, \
opcountersRepl_per_sec.update, opcountersRepl_per_sec.query, opcounters_per_sec.update, \
opcountersRepl_per_sec.command, percent.indexCounters.btree.misses, \
extra_info_per_sec.page_faults, opcountersRepl_per_sec.getmore, opcounters_per_sec.insert, \
opcounters_per_sec.getmore, percent.globalLock.lockTime, network_per_sec.bytesIn
```

Does this answer your questions? If not, please do let me know. Thanks for your time.

**Comment by nathanleiby** [comment]
@rtoma agreed, looks like it was a bug. thanks for the fix!

**Comment by shortdudey123** [comment]
@rtoma got it, thanks!!

**Comment by nathanleiby** [comment]
@shortdudey123 is this good to merge? Thanks!

**Comment by shortdudey123** [comment]
👍

**Comment by nathanleiby** [comment]
@shortdudey123 whom should I ping in order to get this merged? Thanks!

**Comment by shortdudey123** [comment]
@jaingaurav @bmhatfield can one of you guys review please? thanks!

**Comment by rtoma** [comment]
@shortdudey123 @jaingaurav @bmhatfield please merge

**Pull request merged**
