### PR TITLE
handler config parsing fix

### PR DESCRIPTION
**Pull request by hvnsweeting**

### CODE REVIEW

**Comment by hvnsweeting** [comment]
I also tested with just one Handler, without "," at the end, and it still work.

````
# grep 'handlers = ' /etc/diamond/diamond.conf
handlers = diamond.handler.archive.ArchiveHandler
````

**Comment by hvnsweeting** [comment]
NOTICE that I tested with "configobj==5.0.6", older version may handler the right hand side as a String in very old version and as a list only if there is ``,`` in it. By the way, ``configobj==5.0.6`` comes with diamond 4.0 (installed by pip)

**Comment by jaingaurav** [comment]
I'm surprised that it worked with the "," as per the configobj documentation, this would be interpreted as a string. Please see I resolved the issue in pull request #47. This problem was solved in the same manner in the old code.

**Comment by hvnsweeting** [comment]
@jaingaurav  it is because of:

````
In [1]: 'xasfsda'.split(',')
Out[1]: ['xasfsda']

````

so if a string passed, it will return a list after split. Anw, I'm closing this PR as your fix seems more better.

**Pull request closed without merging**
