### PR TITLE
docker_collector.py: support docker python module (issue 687).

### PR DESCRIPTION
**Pull request by gummeah**
Little fix for docker_collector so it can work both with docker-py and docker(newer version of docker-py) python modules.
Fix for [this](https://github.com/python-diamond/Diamond/issues/687) issue.

### CODE REVIEW

**Comment by languitar** [comment]
Any chance to merge this? I am hit by this as well.

**Comment by hslavchev** [comment]
bump

**Comment by gummeah** [comment]
This project was abandoned by developers, so dont waste your time - use something else :) cheers

**Comment by gummeah** [comment]
wow 😱

**Pull request merged**
