### PR TITLE
Enable psutil2 support

### PR DESCRIPTION
**Pull request by joel-airspring**
psutil2 change the memory stat name from ext_memory_info to memory_info_ex.

The PR supports both names and includes a test.

A similar issue: #67
A similar PR: #53

### CODE REVIEW

**Comment by joel-airspring** [comment]
I must be misunderstanding something about python's pep8 because I though lines 225-231 in testprocessresources.py were all indented to 40 characters.

Locally, 'pep8 src/collectors/processresources/test/testprocessresources.py' succeeds.

**Comment by mattrobenolt** [comment]
They are actually 39 characters each. :)

**Comment by joel-airspring** [comment]
Ah!  Thanks.

Downgrading to pep8 1.4.6 showed the error.

**Comment by shortdudey123** [comment]
@joel-airspring can you rebase on master and squash?

**Comment by shortdudey123** [comment]
No longer needed.

**Pull request closed without merging**
