### PR TITLE
Precision fixes

### PR DESCRIPTION
**Pull request by bakerkj**
@jaingaurav Attached is a series of fixes I began discussing in #347.  Please let me know if you think these changes are ok.

Thanks!

-- Ken

### CODE REVIEW

**Comment by jaingaurav** [comment]
Looks great. Could you please squash the commits? At very least squash "fix line length" commit with the lmsesnsors commit. Also squash the 2 ntp commits.

**Comment by bakerkj** [comment]
@jaingaurav How's that?

**Comment by jaingaurav** [comment]
Perfect thanks

**Comment by bakerkj** [comment]
thank you

**Pull request merged**
