### PR TITLE
Update jolokia collector to support jolokia behind basic auth

### PR DESCRIPTION
**Pull request by cbeer**
Some Jolokia instances may be protected by basic auth.

Also, add the ability to override Python's default user-agent, as some versions of jolokia key off the user agent to decide whether to use basic auth (e.g. only support Basic Auth if `curl` is asking..).  See https://issues.jboss.org/browse/ENTESB-2418

### CODE REVIEW

**Comment by cbeer** [comment]
Do you have any suggestions for testing this? I took the basic auth code from the monit collector, but that doesn't seem to be tested there either..

**Comment by cbeer** [comment]
Please do let me know if there's a better way to test the authentication configuration.

**Comment by caskolkm** [comment]
Any chance of merging this?

**Comment by jaingaurav** [comment]
PR #104 has been merged. Is this diff still needed?

**Comment by josegonzalez** [comment]
Closing as #104 has been merged and no one responded to @jaingaurav.

**Pull request closed without merging**
