### PR TITLE
Fix processresource memory collect

### PR DESCRIPTION
**Pull request by hvnsweeting**
I also update the doc and remove some configs that I think are obsoleted.

### CODE REVIEW

**Comment by kormoc** [comment]
You can use assertPublishedMetric without an expected value and it'll only assert if it wasn't published. That should work, no?

**Comment by hvnsweeting** [comment]
after rethought, I think this should using mock data same as all other collectors.

**Comment by jaingaurav** [comment]
ping ping could this please be merged?

**Comment by jaingaurav** [comment]
@mattrobenolt: ping

**Comment by mattrobenolt** [comment]
Is there a reason to not also leave the `ext_memory_info` key for older versions? It seems that it'd gracefully work if both keys are present.

**Comment by jaingaurav** [comment]
That would work too as that is what PR #67 tried to do. I guess you could take in part of that PR followed by this. I can make a clean PR for you if you'd like with all the cherry-picks of each of the authors.

**Comment by shortdudey123** [comment]
No longer needed.

**Pull request closed without merging**
