### PR TITLE
Add support for MemoryCollector to collect percent

### PR DESCRIPTION
**Pull request by alde**
Also refactor the class slightly, breaking the branching off into two
separate methods.

### CODE REVIEW

**Comment by jaingaurav** [comment]
@alde Which kernel/OS are you using? I don't see this on my /proc/meminfo Also can't seem ti see it in the linux sources:

http://lxr.free-electrons.com/source/fs/proc/meminfo.c

**Comment by alde** [comment]
That's why it's being calculated by data that is available. I didn't want to do those calculations in Graphite, because I felt like it would make more sense to have them sent in.

**Comment by jaingaurav** [comment]
Hrm, so I guess it's a bit odd because the _KEY_MAPPING list is used in the /proc/meminfo code path.

So my view on this is collectors should not try to compute values as this is something that graphite is quite capable of doing either with the carbon-aggregator or by having a query that performs the calculations. Diamond collectors should really try to send raw values wherever possible. This simplifies collectors and makes leads to less confusion regarding how a collector may have computed a value.

Please let me know if there is something I'm missing regarding your use case.

**Comment by alde** [comment]
Well, we use Diamond to monitor mesos-slaves, so we try to aggregate memory usage using a query containing a wildcard for the server number, for example 'server.mesos-slave-*.memory.MemFree', to not have to make a hundred different entries manually.

Given that, graphite can't do calculations on matching names automatically (or at least not in any way that I've found).

**Comment by jaingaurav** [comment]
@alde You might want to take look at the latest map/reduce functionality added in graphite:

http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.reduceSeries

Also, I believe if you put carbon-aggregator before your carbon-cache you may be able to perform this calculation.

**Comment by alde** [comment]
Oh, thanks. I will check on that.

Thanks :)

**Comment by jaingaurav** [comment]
@alde alright closing this PR for now. Please feel free to re-open or comment if you are still having issues.

**Pull request closed without merging**
