### PR TITLE
Add fibt2 and qm stats to xfs collector

### PR DESCRIPTION
**Pull request by fiskn**
Add fibt2 and qm stats, without them a invalid key error occurs. Seen on Kernel 4.2+

### CODE REVIEW

**Comment by shortdudey123** [comment]
Can you update the tests accordingly to validate the addition?

**Comment by shortdudey123** [comment]
Looking good :)

**Comment by shortdudey123** [comment]
@jaingaurav @bmhatfield can you review?

**Comment by jaingaurav** [comment]
Looks great thanks!

**Pull request merged**
