### PR TITLE
Multi blackwhitelist

### PR DESCRIPTION
**Pull request by ethan-eb**
I adjusted collector.py code to handle multiple whitelists or
blacklists, and used the HadoopCollector to test the changes.

The collector.process_config now ensures that
collector.config['metrics_whitelist'](and blacklist) is either a list
of regex objects, or an empty list.

collector.metric_allowed is based on work from a previous commit and is
now generalized enough use either with path or name filtering. It now
checks white/black lists in a loop. The collector.publish uses that same
method now to avoid code duplication.

For testing I first confirmed that I broke tests by making
'metrics_blacklist' in testhadoop.py a tuple (because the code expected
a string). I then made my changes and confirmed the test was still
broken because the newly blacklisted path was not in the list of
expected metrics. I then edited expected.pkl to remove that metric, and
confirmed tests passed once again.

### CODE REVIEW

**Comment by ethan-eb** [comment]
So this PR includes the fix for python-diamond/Diamond#230 and python-diamond/Diamond#234 because I wanted to build on the changes in the #234 fix. If you all don't want this multi white/blacklists stuff, there is a separate PR which is *only* the #234 fix : https://github.com/python-diamond/Diamond/pull/244

**Comment by nathanleiby** [comment]
:100: for making this generic in collectors. 

I faced a similar issue in https://github.com/python-diamond/Diamond/pull/236 and think a generic whitelist/blacklist for handlers would also be useful!

**Comment by ebpitts** [comment]
The test failures reported by Travis look spurious.

https://travis-ci.org/python-diamond/Diamond/jobs/94716665 = pep8 violations in collectors not touched by this PR

https://travis-ci.org/python-diamond/Diamond/jobs/94716664 = pep8 violations plus some strange import and test function errors, maybe related to python 2.6?

Is this mergeable?

**Comment by shortdudey123** [comment]
@josegonzalez or @jaingaurav can you guys review this as well since its a change to a core config options?

**Pull request merged**
