### PR TITLE
adapt to changed psutil functions interface

### PR DESCRIPTION
**Pull request by grobian**
psutil functions were renamed, apply those changes so Diamond works again using latest psutil.

### CODE REVIEW

**Comment by josegonzalez** [comment]
This breaks existing installations, so maybe you want to check if `hasattr` before using the new versions, else use the old?

**Comment by grobian** [comment]
Is it really worth doing so?  Can't we require a newer version?  On Linux Diamond still uses its own parsing, so never uses psutil, isn't it?

**Comment by jaingaurav** [comment]
@grobian: I think we need diamond to be compatible with both the new and the old one since it it possible that a user may not be able to upgrade due to some other dependancies on the old pustules.

**Comment by shortdudey123** [comment]
Can you address the above concern and squash your commits?

**Comment by grobian** [comment]
No, I've moved on and no longer have this, feel free to use parts that you want though.

**Pull request closed without merging**
