### PR TITLE
[mesos] Do not assume that Mesos always run on http.

### PR DESCRIPTION
**Pull request by nihn**

### CODE REVIEW

**Comment by shortdudey123** [comment]
Can you update the doc and add scheme checking to the tests?

**Comment by nihn** [comment]
@shortdudey123 done

**Comment by shortdudey123** [comment]
Cool, can you update the doc as well?

**Comment by shortdudey123** [comment]
Looks good!  Can you squash the commits please :)

**Comment by shortdudey123** [comment]
Awesome
@jaingaurav @bmhatfield can one of you guys review?

**Pull request merged**
