### PR TITLE
AuroraCollector: Initial commit

### PR DESCRIPTION
**Pull request by bmhatfield**
This collects metrics from the https://github.com/apache/aurora scheduler's metrics page.

### CODE REVIEW

**Comment by MichaelDoyle** [comment]
LGTM

**Comment by bmhatfield** [comment]
@mattrobenolt - thoughts on merging this?

**Comment by mattrobenolt** [comment]
I don't know anything about Aurora, but this seems reasonable. I could only recommend "add tests plz".

**Comment by bmhatfield** [comment]
@mattrobenolt u can haz tests, i can haz merge?

**Comment by mattrobenolt** [comment]
thx :cake: :sparkles:

**Pull request merged**
