### PR TITLE
Don't join prefix if empty in Collector.get_metric_path.

### LINKED ISSUE #123: Names of some metrics prefixed with dot
Seems that `Collector.get_metric_path` is guilty. Last return in this method `return '.'.join([prefix, path, name])` uses prefix which is blank in these cases. Sample metrics from StatsD's logs:

```
6 Mar 09:16:58 - DEBUG: .memcached.localhost.threads:4|g
6 Mar 09:16:58 - DEBUG: .network.eth0.tx_frame:0.0|g
6 Mar 09:16:58 - DEBUG: .iostat.sda5.writes_byte:2920448.0|g
6 Mar 09:16:58 - DEBUG: .diskspace._var.inodes_avail:6803010|g
6 Mar 09:16:58 - DEBUG: .loadavg.processes_total:806|g
```

It causes some issues later on when in e.g. relay-rules.conf for Graphite regexp needs to be added as for some metrics we have ".." inside.

### PR DESCRIPTION
**Pull request by nihn**
Fixes #123

### CODE REVIEW

**Comment by Nihn** [comment]
ping :)

**Comment by mlowicki** [comment]
@mattrobenolt  could you have a look?

**Comment by mattrobenolt** [comment]
Can I get a test for this? :)

**Comment by Nihn** [comment]
ping again :).

**Comment by Nihn** [comment]
@mattrobenolt could you have a look again? :)

**Comment by mlowicki** [comment]
@mattrobenolt @bmhatfield  could you take a look? Tests have been added.

**Comment by mlowicki** [comment]
@mattrobenolt @jaingaurav ping.

**Comment by josegonzalez** [comment]
Thanks for the pull request!

**Pull request merged**
