### PR TITLE
Add Basic/Shield auth to elasticsearch collector

### PR DESCRIPTION
**Pull request by okushchenko**
Current implementation of Elasticsearch collector has no ability to authenticate against Shield plugin for Elasticsearch, so I've added optional parameters to authenticate with.
I'm using this version of collector in prod right now and it works just fine.

### CODE REVIEW

**Comment by shortdudey123** [comment]
Can you update the testing and doc as well?

**Comment by okushchenko** [comment]
@shortdudey123 Can you help me with the testing part - what tests should I write?

**Comment by shortdudey123** [comment]
I would duplicate one of the `real_data` tests and add in the username / password auth in the mock and make sure that it passes those variables in the request and gets the data back

**Comment by hamelg** [comment]
I need this enhancement. What about this test : 
```
--- a/src/collectors/elasticsearch/test/testelasticsearch.py
+++ b/src/collectors/elasticsearch/test/testelasticsearch.py
@@ -119,6 +119,12 @@ class TestElasticSearchCollector(CollectorTestCase):
         self.assertPublishedMany(publish_mock, metrics)
 
     @patch.object(Collector, 'publish')
+    def test_should_work_with_real_data_and_basic_auth(self, publish_mock):
+        self.collector.config["user"] = "user"
+        self.collector.config["password"] = "password"
+        self.test_should_work_with_real_data()
+
+    @patch.object(Collector, 'publish')
     def test_should_work_with_real_data_logstash_mode(self, publish_mock):
         returns = [
             self.getFixture('stats'),
```

**Comment by shortdudey123** [comment]
@hamelg looks like that would probably work if not close to it

**Comment by hamelg** [comment]
What's missing to accept this request ?

**Comment by shortdudey123** [comment]
I still don't see any testing or doc as requested

**Comment by hamelg** [comment]
For testing, see my comment https://github.com/python-diamond/Diamond/pull/477#issuecomment-267843330
For doc, adding user/password in config_help.update() is not sufficient ?

I can't amend this request and okushchenko has given up.
How can I do ?
May i recreate another request ?

**Comment by shortdudey123** [comment]
> For testing, see my comment #477 (comment)

This should be added to the PR, not a comment

> For doc, adding user/password in config_help.update() is not sufficient ?

`docs/collectors/ElasticSearchCollector.md` needs to be updated

@okushchenko can you update as requested?

**Comment by kormoc** [comment]
Actually, `make docs` should update the fines in the `docs/` directory

https://github.com/python-diamond/Diamond/blob/master/Makefile#L39

**Comment by okushchenko** [comment]
I've incorporated a test proposed by @hamelg, many thanks! Also, I've updated the docs.

**Comment by okushchenko** [comment]
@shortdudey123 is there anything more I can do to make this PR mergeable?

**Pull request merged**
