### PR TITLE
Add regex bean matching, and regex key search/replace to normalize names

### PR DESCRIPTION
**Pull request by sbrynen**
This patch adds two more config items to the JolokiaCollector.conf
mbeansre:  works like mbeans: but matches with regularexpressions
rewrite: which allows rewrite pairs in order to rename collected keys before data is passed to the handler

### CODE REVIEW

**Comment by kormoc** [comment]
Can you also rebase your PR with current master? Thanks!

**Comment by sbrynen** [comment]
it's all re-based now (and pep8 fixed)

**Comment by sbrynen** [comment]
Any chance we can get this merged in now??

**Comment by sbrynen** [comment]
I've created a new pull request as this was so old

**Pull request closed without merging**
