### PR TITLE
the librato handler doesn't support metric prefix

### PR DESCRIPTION
**Pull request by rocktavious**
This will give you the ability to apply the prefix to the metric name - diamond's default metric prefix is "systems"

### CODE REVIEW

**Comment by rocktavious** [comment]
This error is not a problem with my pull request.

**Comment by jaingaurav** [comment]
Re-ran travis-ci and things look great. Could you please squash your commits and I'll merge them.

**Comment by rocktavious** [comment]
I have squashed all changes.

**Comment by jaingaurav** [comment]
Thanks, merged

**Pull request merged**
