### PR TITLE
Added delimiter option to ipmisensor.py

### PR DESCRIPTION
**Pull request by sirtux**
Added an option to impisensor.py for having a flexible delimiter configuration, defaulting to '.', which is the current default.
Change runs through the current tests, but a test case for a dynamic delimiter has to be written, but I have no idea howto implement that.

### CODE REVIEW

**Comment by jaingaurav** [comment]
This looks great. However could you add a test case which includes sample output from the HP IPMI?

**Comment by sirtux** [comment]
How do I add a second test case? All tests I have seen so far only have one fixture - can I simply create a second test file?

**Comment by jaingaurav** [comment]
Just duplicate the test_should_work_with_real_data function in testipmisensor.py within the same file and change the getFixture('ipmitool.out') call to return your file instead. For further reference, you can look at some other test case files such as testsmart.py.

**Comment by sirtux** [comment]
Here we go with the added tests

**Comment by jaingaurav** [comment]
:+1: :+1: :+1: :+1:

Thanks a lot! This looks really good. The test cases really help provide a basis for this change.

**Comment by sirtux** [comment]
Hi all, do you have an idea when this request will be merged? I would like to go back to create packages for us from the master branch, and no longer our own...

Or is anything missing?

Thanks,
Tom

**Comment by jaingaurav** [comment]
Code has been merged. Thanks for the work and I apologize regarding the late merge.

**Pull request merged**
